### ISSUE TITLE
Error when running yarn-update

### ISSUE THREAD

**Issue by zerocode** [torifat/yarn-update#3]
I'm getting the following error when running 'yarn-update'. 

yarn --version
0.24.6

node --version
v6.10.3

- Checking for updated packages.events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

**Comment by torifat** [comment]
Please read the README.
